<a href="https://colab.research.google.com/github/23f3003467/Project1/blob/main/Bengio's%202003%20paper%20on%20NLP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Bengio's 2003 paper on nlp


In [2]:
import torch
import torch.nn as nn

In [3]:
class NNLM(nn.Module):

    def __init__(self, vocab_size, embed_dim, context_size, hidden_dim):

        super().__init__()

        # Embedding matrix
        self.embedding = nn.Embedding(vocab_size, embed_dim)

        # Hidden layer
        self.fc1 = nn.Linear(context_size * embed_dim,
                             hidden_dim)

        # Output layer
        self.fc2 = nn.Linear(hidden_dim,
                             vocab_size)

    def forward(self, x):

        # x shape = (batch_size, context_size)

        x = self.embedding(x)

        # shape
        # (batch_size, context_size, embed_dim)

        x = x.view(x.size(0), -1)

        # concatenate embeddings

        x = torch.tanh(self.fc1(x))

        logits = self.fc2(x)

        return logits

In [4]:
model = NNLM(
    vocab_size=10000,
    embed_dim=100,
    context_size=3,
    hidden_dim=300
)

In [5]:
model

NNLM(
  (embedding): Embedding(10000, 100)
  (fc1): Linear(in_features=300, out_features=300, bias=True)
  (fc2): Linear(in_features=300, out_features=10000, bias=True)
)

In [6]:
word2id = {
    "I":0,
    "love":1,
    "eating":2,
    "apples":3
}

In [7]:
x = torch.tensor([[0,1,2]])

In [8]:
y = torch.tensor([3])

In [9]:
logits = model(x)

In [10]:
logits

tensor([[-0.2630, -0.1681,  0.2686,  ...,  0.3006, -0.4133, -0.1148]],
       grad_fn=<AddmmBackward0>)

In [11]:
criterion = nn.CrossEntropyLoss()

loss = criterion(logits, y)

In [12]:
optimizer = torch.optim.Adam(
    model.parameters(),
    lr=0.001
)

In [13]:
for epoch in range(100):

    optimizer.zero_grad()

    logits = model(x)

    loss = criterion(logits, y)

    loss.backward()

    optimizer.step()

In [14]:
embedding = nn.Embedding(10000,100)


In [15]:
embedding

Embedding(10000, 100)

In [16]:
import numpy as np


In [17]:
vocab_size = 6
embedding_dim = 4
context_size = 3
hidden_size = 5

In [18]:
word2id = {
    "I":0,
    "love":1,
    "eating":2,
    "apples":3
}

In [19]:
E = np.random.randn(vocab_size, embedding_dim)

In [20]:
E

array([[-0.17681522, -0.02490482,  1.31892201,  0.5393125 ],
       [-0.97794078, -1.66916835,  1.67778639, -1.89502033],
       [ 0.06905337, -0.02861703, -0.70597668,  0.34624153],
       [-0.79370164,  0.26322363,  0.24282857,  1.45249649],
       [ 0.18818125,  0.55034057,  1.38560958,  0.29486054],
       [ 0.62997032, -1.16320777,  0.53672474, -1.55867782]])

In [21]:
W1 = np.random.randn(hidden_size, context_size * embedding_dim)

b1 = np.zeros((hidden_size,1))

In [22]:
W2 = np.random.randn(vocab_size, hidden_size)

b2 = np.zeros((vocab_size,1))

In [23]:
context = [0,1,2]

In [24]:
embeddings = E[context]
embeddings

array([[-0.17681522, -0.02490482,  1.31892201,  0.5393125 ],
       [-0.97794078, -1.66916835,  1.67778639, -1.89502033],
       [ 0.06905337, -0.02861703, -0.70597668,  0.34624153]])

In [25]:
x = embeddings.reshape(-1,1)

In [38]:
x

array([[ 0.00496714],
       [-0.00138264],
       [ 0.00647689],
       [ 0.0152303 ],
       [-0.00234153],
       [-0.00234137],
       [ 0.01579213],
       [ 0.00767435],
       [-0.00469474],
       [ 0.0054256 ],
       [-0.00463418],
       [-0.0046573 ],
       [ 0.00241962],
       [-0.0191328 ],
       [-0.01724918]])

In [26]:
z1 = W1 @ x + b1

In [27]:
# Calculate the hidden layer output (h) using tanh activation
h = np.tanh(z1)
print("Hidden layer output (h):")
print(h)

# Calculate the input to the output layer (z2)
z2 = W2 @ h + b2
print("\nOutput layer input (z2):")
print(z2)

# Apply softmax to get the output probabilities (y_hat)
def softmax(x):
    exp_x = np.exp(x - np.max(x)) # Subtract np.max(x) for numerical stability
    return exp_x / np.sum(exp_x, axis=0)

y_hat = softmax(z2)
print("\nOutput probabilities (y_hat):")
print(y_hat)

# The sum of probabilities should be 1
print("\nSum of probabilities:", np.sum(y_hat))

Hidden layer output (h):
[[-0.98220354]
 [-0.93671362]
 [ 0.9999534 ]
 [ 0.99995049]
 [ 0.30847411]]

Output layer input (z2):
[[-0.77757139]
 [ 0.66194886]
 [ 0.58618641]
 [-1.903263  ]
 [ 1.64760579]
 [ 0.970163  ]]

Output probabilities (y_hat):
[[0.03773617]
 [0.15919651]
 [0.14758096]
 [0.01224267]
 [0.42657845]
 [0.21666524]]

Sum of probabilities: 1.0


In [28]:
import numpy as np

vocab_size = 6
embedding_dim = 4
context_size = 3
hidden_size = 5

# Parameters
E = np.random.randn(vocab_size, embedding_dim)

W1 = np.random.randn(hidden_size,
                     context_size * embedding_dim)

b1 = np.zeros((hidden_size,1))

W2 = np.random.randn(vocab_size,
                     hidden_size)

b2 = np.zeros((vocab_size,1))

# Context
context = [0,1,2]

# Embedding lookup
embeddings = E[context]

# Concatenate
x = embeddings.reshape(-1,1)

# Hidden layer
h = np.tanh(W1 @ x + b1)

# Output
logits = W2 @ h + b2

# Softmax
def softmax(x):
    e = np.exp(x - np.max(x))
    return e / np.sum(e)

prob = softmax(logits)

print(prob)

[[0.10249725]
 [0.05708   ]
 [0.73234076]
 [0.08634376]
 [0.00892346]
 [0.01281477]]


In [29]:
X = np.array([0,1,2])
y = 3

In [30]:
import numpy as np

np.random.seed(42)

vocab_size = 4
embedding_dim = 5
context_size = 3
hidden_size = 6

E = np.random.randn(vocab_size, embedding_dim)*0.01

W1 = np.random.randn(hidden_size,
                     context_size*embedding_dim)*0.01

b1 = np.zeros((hidden_size,1))

W2 = np.random.randn(vocab_size,
                     hidden_size)*0.01

b2 = np.zeros((vocab_size,1))

In [31]:
# X is the id of words which are used as input
embeddings = E[X]

x = embeddings.reshape(-1,1)

z1 = W1 @ x + b1

h = np.tanh(z1)

z2 = W2 @ h + b2

In [32]:
def softmax(z):
    z = z - np.max(z)
    exp = np.exp(z)
    return exp/np.sum(exp)

In [33]:
probs=softmax(z2)
probs

array([[0.25000216],
       [0.25000065],
       [0.24999996],
       [0.24999724]])

In [34]:
loss = -np.log(probs[y,0])

print(loss,probs[y,0])

1.386305404507998 0.24999723916821764


In [35]:
dz2 = probs.copy()
dz2[y] -= 1

dW2 = dz2 @ h.T
db2 = dz2

dh = W2.T @ dz2
dz1 = dh * (1 - h*h)

dW1 = dz1 @ x.T
db1 = dz1

dx = W1.T @ dz1
dx = dx.reshape(context_size, embedding_dim)

In [39]:
dx.shape
lr=0.01

In [43]:
for i,word in enumerate(X):
  E[word] -= lr * dx[i]


In [44]:
embeddings = E[X]

x = embeddings.reshape(-1,1)

z1 = W1 @ x + b1

h = np.tanh(z1)

z2 = W2 @ h + b2

In [45]:
probs=softmax(z2)
probs

array([[0.25000215],
       [0.25000065],
       [0.24999995],
       [0.24999724]])

In [48]:
epochs=100
for epochs in range(epochs):
  embeddings = E[X]

  x = embeddings.reshape(-1,1)

  z1 = W1 @ x + b1

  h = np.tanh(z1)

  z2 = W2 @ h + b2
  probs=softmax(z2)
  loss = -np.log(probs[y,0])
  dz2 = probs.copy()
  dz2[y] -= 1

  dW2 = dz2 @ h.T
  db2 = dz2

  dh = W2.T @ dz2
  dz1 = dh * (1 - h*h)

  dW1 = dz1 @ x.T
  db1 = dz1

  W2 -= lr * dW2
  b2 -= lr * db2

  W1 -= lr * dW1
  b1 -= lr * db1

  dx = W1.T @ dz1
  dx = dx.reshape(context_size, embedding_dim)
  for i,word in enumerate(X):
    E[word] -= lr * dx[i]


In [49]:
embeddings = E[X]

x = embeddings.reshape(-1,1)

z1 = W1 @ x + b1

h = np.tanh(z1)

z2 = W2 @ h + b2

probs=softmax(z2)
probs

array([[0.18544272],
       [0.18542709],
       [0.18543823],
       [0.44369196]])

In [50]:
predicted_id = np.argmax(probs)

print(predicted_id)


3
